misc/docker/seqrepo.df
Setting the seqrepo data dir via environment variable gives docker users the ability to override the path to fit their use cases.
=> set data dir path via environment variable

misc/docker/seqrepo.df
The most recent biopython and pysam libraries require two more packages to build.
=> Add two Debian packages to enable Docker build

biocommons/seqrepo/fastadir/fastadir.py, biocommons/seqrepo/seqaliasdb/seqaliasdb.py, biocommons/seqrepo/seqrepo.py
Set to False by default but now it is a configurable option
=> Expose check_same_thread option for sqlite connection 

biocommons/seqrepo/cli.py, tests/test_cli.py
Attempting to raise the original `IOError` instead raised a `KeyError` as the key in the formatted string was not provided. This fix also
=>  #45: Improve coverage of init function in cli module and fix key in formatted exception message

tests/test_fastadir.py
Test 1) sets schema_version==2, to trigger RuntimeError during instantiation 
Test 2) sets writeable=False to trigger RuntimeError
=> Add 2 tests to test_fastadir.py

biocommons/seqrepo/py2compat/__init__.py
The latest stable version of RHEL/CentOS is still on Python 3.4, which is preventing us from using seqrepo on our servers. This commit makes the Python compatibility code more generic so that seqrepo can work on Python 3.4 and earlier.
=> Use custom commonpath implementation on Python 3.4

src/biocommons/seqrepo/fastadir/fastadir.py, src/biocommons/seqrepo/seqaliasdb/seqaliasdb.py, tests/test_seqrepo.py
This enables the possibility to use another SQL database for backend.
=> SQLite usage is changed to more Python DB API 2.0 compatible. 

pyproject.toml, setup.cfg
1-for-1 mirroring of @andreasprlic PR on HGVS: https://github.com/biocommons/hgvs/pull/713
FWIW, more and more Python tools support configuration in `pyproject.toml`, might be nice to consolidate the rest of the setuptools configs in `setup.cfg` + some of the other files (`pytest.ini`, etc)
=> build: fix dynamic dependencies for newer setuptools versions

.flake8, .github/workflows/python-package.yml, .pre-commit-config.yaml, Makefile, README.md, pyproject.toml, src/biocommons/seqrepo/_internal/logging_support.py, src/biocommons/seqrepo/_versionwarning.py, src/biocommons/seqrepo/cli.py, src/biocommons/seqrepo/config.py, src/biocommons/seqrepo/dataproxy.py, src/biocommons/seqrepo/fastadir/__init__.py, src/biocommons/seqrepo/fastadir/fabgz.py, src/biocommons/seqrepo/fastadir/fastadir.py, src/biocommons/seqrepo/fastaiter/__init__.py, src/biocommons/seqrepo/fastaiter/fastaiter.py, src/biocommons/seqrepo/seqaliasdb/__init__.py, src/biocommons/seqrepo/seqaliasdb/seqaliasdb.py, src/biocommons/seqrepo/seqrepo.py
* add flake8 config from template
* add pre-commit settings from template
* apply flake8/black/isort
* re-add linting/formatting check CI action
=> style: apply updated style configs from template

src/biocommons/seqrepo/cli.py
=> Do not preserve permissions when pulling an instance with rsync

docs/store.rst
close #156 
I missed this fairly obvious behavior because we were using `store` to access in subsequent `ga4gh.enref` calls, and didn't need it to outlive the session -- but this is probably important.
=> docs: add note about commit()

.github/workflows/python-package.yml, .pre-commit-config.yaml, Makefile, pyproject.toml, src/biocommons/seqrepo/cli.py, src/biocommons/seqrepo/fastadir/fabgz.py, src/biocommons/seqrepo/fastadir/fastadir.py, src/biocommons/seqrepo/seqaliasdb/seqaliasdb.py
Per an earlier discussion, this implements just the format half of `ruff`, removing `black`. Because `ruff` handles things like `isort` on the lint side, this PR doesn't address that yet.
=> style: format with Ruff

README.md, pyproject.toml, src/biocommons/seqrepo/cli.py
close #147 
Per brief discussion on a biocommons call the other day -- this PR moves the dependency (ipython) required for shell functionality to an optional group and adds a bit of information to the ImportError if ipython is unavailable.
I would expect this to impact a pretty small number of users, but it is a breaking change.
=> build!: move ipython/repl functionality to optional dependency group

src/biocommons/seqrepo/fastadir/fastadir.py, src/biocommons/seqrepo/seqaliasdb/seqaliasdb.py
close #127 
* remove two cases of timezone-related deprecations -- one regarding default sqlite3 management of time type conversions back into python, and another from the `utcnow()` method
I'd appreciate some input about where to register the sqlite3 timestamp converter -- I put it in `seqaliasdb.py` since that seems like the place where it's most important to be pulling out precisely formatted strings but wasn't totally sure. It's sort of weird that the sqlite3 module has you register these things to some global context (?) rather than individual connections.
=> refactor: resolve timezone-related python 3.12 deprecations

.style.yapf
Probably my bad for not removing this during the switch to Ruff earlier. This PR deletes an unused YAPF config file.
=> chore: remove unused YAPF config

.github/workflows/python-package.yml
When attempting to release 0.6.10, github actions deploy to pypi failed with this:
```
Digest: sha256:95f6a263932ad985f1b29df33a1748fddb8b92b46b7c95a2a3b3c6c7506096a3
Status: Downloaded newer image for ghcr.io/pypa/gh-action-pypi-publish:release-v1
Warning: The workflow was run with the 'attestations: true' input, but an explicit password was also set, disabling Trusted Publishing. As a result, the attestations input is ignored.
Warning: Trusted Publishers allows publishing packages to PyPI from automated environments like GitHub Actions without needing to use username/password combinations or API tokens to authenticate with PyPI. Read more: https://docs.pypi.org/trusted-publishers
Warning: A new Trusted Publisher for the currently running publishing workflow can be created by accessing …
```
=> switch deploy to use trusted publisher rather than token/password

.github/workflows/python-package.yml, Makefile, pyproject.toml
* ensure explicit dependency is available
* move testing-related dependencies out of `dev` group and only install them during the `test` job so that the error in #181 would've been caught: https://github.com/biocommons/biocommons.seqrepo/actions/runs/13936166604/job/39004394961
=> build: require typing_extensions

.gitignore, Makefile, README.md, pyproject.toml
I chose to unpin developer tools because the frustration of having these fail due to staleness is likely more common and severe than having them fail due to newness.
=> unpin developer tools in order to keep these up-to-date

.github/workflows/python-package.yml, .pre-commit-config.yaml, Makefile, pyproject.toml, setup.py, src/biocommons/seqrepo/cli.py, src/biocommons/seqrepo/config.py, src/biocommons/seqrepo/fastadir/fastadir.py, src/biocommons/seqrepo/seqaliasdb/seqaliasdb.py, tests/test_cli.py, tests/test_fastadir.py, tests/test_seqrepo.py
Minor improvements (IMO) to rsync handling on mac, including:
- use standard exceptions
- find rsync in PATH rather than hardcoding (but allow for absolute path --rsync-exe argument)
- test for openrsync more affirmatively
In the course of doing this, I had to address some organic growth and skew between Makefile, pre-commit, and github workflows.
=> 186 rsync issues on mac again

pyproject.toml
Previously in main:
```
> make build
⋮
Successfully built biocommons_seqrepo-0.6.12.dev4+g6ecc920.tar.gz and biocommons.seqrepo-0.6.12.dev4+g6ecc920-py3-none-any.whl
```
With this PR:
```
> make build
⋮
Successfully built biocommons_seqrepo-0.6.12.dev5+gdf09046.tar.gz and biocommons_seqrepo-0.6.12.dev5+gdf09046-py3-none-any.whl
```
Notice the wheel was previously `biocommons.seqrepo` and is now `biocommons_seqrepo`.
=> update build tooling and package versions in pyproject.toml
